#!/bin/sh

#
# audstrip -- Strip metadata tags and remove cover from audio file.
#

progname=$(basename $0)
TMP_DIR="/tmp"

err()
{
	echo "$progname: $@" 1>&2
	exit 1
}

usage()
{
	cat 1>&2 <<__EOF__
Usage: $progname [-i extension] file ...

Options:
    -i -- specify extension for backup files (.bak by default).
          When empty string is used, no backup files will be done.
__EOF__
	exit 2
}

do_strip()
{
	local file="$1"
	local tmp_name=$(mktemp -u "$TMP_DIR/XXXXXXXX_$(basename $file)")
	
	ffmpeg -loglevel 8 -i "$file" -map 0:a -c:a copy -map_metadata -1 \
	    "$tmp_name" >/dev/null
	if [ $? -eq 0 ]; then
		backup_ext="bak"
		[ $bak_opt -eq 1 ] && backup_ext="$bak_ext"
		if [ -n "$backup_ext" ]; then
			mv "$file" "$file.$backup_ext"
		fi
		mv "$tmp_name" "$file"
		echo "$file"
	fi
	
}

bak_opt=0
while getopts "i:" o; do
	case $o in
	i)
		bak_opt=1
		bak_ext="$OPTARG"
		;;
	?) usage ;;
	esac
done
shift $((OPTIND - 1))

[ $# -ge 1 ] || usage

for file in $@; do
	[ -f "$file" ] || err "File not found: $file"
done
for file in $@; do
	do_strip "$file"
done
