#!/bin/sh
tar\
 --exclude='.fetchmail.pid'\
 --exclude='dead.letter'\
 --exclude='.cache'\
 --exclude='.npm'\
 --exclude='node_modules'\
 --exclude='.mozilla'\
 --exclude='.config/chromium/**/Cache'\
 --exclude='.config/chromium/**/CacheStorage'\
 --exclude='/home/artembunichev/dev/wsv/m3t'\
 -cJvf /tmp/hom.txz /home/artembunichev 2>&1 |tee /tmp/buh.log
