#!/bin/sh

tar \
 --exclude='.cache' \
 --exclude='.npm' \
 --exclude='.mozilla' \
 --exclude='.kyua' \
 --exclude='.cpan' \
 --exclude='.ccache' \
 --exclude='.sujournal' \
 --exclude='.sh_history' \
 --exclude='node_modules' \
 --exclude='chromium/**/Cache' \
 --exclude='chromium/**/CacheStorage' \
 --exclude='wsv/m3t' \
-cJvf /tmp/bup.txz \
 /boot/loader.conf \
 /boot/loader/kernel.good \
 /boot/loader/kernel.install \
 /etc \
 /usr/local/etc \
 /usr/local/src \
 /root \
 /home \
2>&1 |tee /tmp/bup.log
