#!/bin/sh

#
# can -- named cat(1).
#
# cat(1) files, but also print their names.
# I consider it solely as visual tool.
#

idx=0
for file in "$@";do
	echo "==> $file <=="
	cat "$file"
	idx=$((idx+1))
	if [ $idx != $# ]; then
		echo
	fi
done
