#!/bin/sh
#this is a script for compiling files for
#C-language program.
#execute it from the project's directory.
#if a compilation of a specific file(s) is desired,
#specify it's (their's) name(s) without .c 
#extension as argument(s).
#it works only at 1-level depth.
if [ "$#" -ne 0 ]
then srcs=$(echo "$@"|sed 's/$/\.c/')
else srcs=$(find . -type f -name "*\.c" -maxdepth 1)
fi
if [ -z "$srcs" ];then
	echo "cmp: nothing to compile." 1>&2
	exit 1
fi
opts=""
if [ -f o.cmp ]
	then opts=$(cat o.cmp|perl -pe "s/\n/ /gm")
fi
for src in $srcs;do
	if [ ! -f "$src" ];then
		echo "cmp: no such file: $src." 1>&2
		exit 1
	fi
	out=$(echo "$src"|sed 's/\.c//')
	cc -o "$out" "$src" -I/usr/local/include -L/usr/local/lib $opts &&\
	echo "cmp: $(basename $src) -> $(basename $out)"
done
