#!/bin/sh

# dof -- place symlinks to dot-file in HOME directory.


bas="$HOME"
dof=".dof"

cd "$bas/$dof"
kids=$(find . -not -path "./.git/*" -type f|sed "s/^\.\///g")
for kid in $kids;do
	mkdir -p $(dirname "$bas/$kid")
	ln -s -f "$bas/$dof/$kid" "$bas/$kid"
done
