#!/bin/sh
#place dot files.
bas="/home/artembunichev"
dof=".dof"
cd "$bas/$dof"
kids=$(find . -type f|sed "s/^\.\///g")
for kid in $kids;do
mkdir -p $(dirname "$bas/$kid")
ln -s -f "$bas/$dof/$kid" "$bas/$kid"
done
