#!/bin/sh

#
# esub -- extract a zip(1) archive with subtitles for a film.
#

file="$1"
if [ -z "$file" ]; then
	echo "[esub]: specify an archive file." 1>&2
	exit 1
fi

unzip "$file" >/dev/null
if [ $? -ne 0 ]; then
	exit
fi

rm -f *\.nfo
mv *\.srt sub.srt \
    && rm -f "$file"
