#!/bin/sh

#
# fw -- find files containing pattern. Case-sensitive.
# fwj -- case-insensitive version of `fw'.
#

progname=$(printf "$0" |sed 's/.*\///')

if [ -z "$@" ]; then
	echo "Usage: $progname pattern [path ...]" 1>&2
	exit 1
fi

last_name_char=$(printf "$progname" |sed 's/\.sh//' |tail -c1)
if [ "$last_name_char" = "j" ]; then
	case_flag="-i"
else
	case_flag=""
fi

grep --exclude-dir=".git" -RIl $case_flag "$@"
