#!/bin/sh

# a script of mine that
# excludes specified files
# from being tracked by git(1).


list=0
if [ "$#" -eq 0 ];then
	list=1
fi

if [ ! -d .git ];then
	echo "[giig]: not a git repository." 1>&2
	exit 1
fi

if [ ! -f .gitignore ];then
	if [ "$list" = "1" ]
		then
			echo "[giig]: no .gitignore file."
			exit 0
		else touch .gitignore
	fi
fi

if [ "$list" = "0" ]
	then
		fls=$(echo -n "$@" |tr " " "\n")
		echo "$fls" >>.gitignore
	else cat .gitignore
fi
