#!/bin/sh

#
# mp32ogg -- convert all the .mp3 files to .ogg.
#
# Takes a list of .mp3 files to be converted as an argument.
#


if [ ! -x /usr/local/bin/ffmpeg ]; then
	echo "[mp32ogg]: ffmpeg(1) is needed to run this script" 1>&2
	exit 1
fi

mp3s="$@"

if [ -z "$mp3s" ]; then
	echo "Usage: mp32ogg mp3_file ..." 1>&2
	exit 1
fi

for mp3 in $mp3s; do
	if [ ! -f "$mp3" ]; then
		echo "[mp32ogg]: "$mp3" does not exist" 1>&2
		continue
	fi
	ogg=$(echo "$mp3" |sed 's/\.mp3$/\.ogg/')
	if [ -f "$ogg" ]; then
		echo "[mp32ogg]: .ogg version of $mp3 already exists" 1>&2
		continue
	fi
	echo "[mp32ogg]: $mp3 -> $ogg" 1>&2
	/usr/local/bin/ffmpeg -loglevel 8 -i "$mp3" "$ogg"
done
