#!/bin/sh

#
# myip -- display information about public IP address.
#

progname=$(basename "$0")

CHECK_URL="zx2c4.com/ip"
GETTER_PROG="curl"

err()
{
	echo "$progname: $@" 1>&2
	exit 1
}

[ -x $(which "$GETTER_PROG") ] || err "$GETTER_PROG is required"
curl "$CHECK_URL"
