#!/bin/sh

#
# pkg-tree -- display a tree-like structure for packages in FreeBSD.
#
# It makes use of pkg-info(8) in order to recursively obtain
# either package dependencies (`-d' switch) or dependents (`-r')
# and display them as a tree.  The script may go recursive (infinite).
#
# You can modify `tab' variable in this script to fit your needs.
#


print_tree() {
(
	target="$1"
	ind="$2"
	info=$(pkg info $mode "$target")
	IFS="
"
	for line in $info; do
		if ! echo "$line" |grep -q "	"; then
			if [ $first = 1 ]; then
				echo "$line" |sed 's/:$//'
				first=0
			fi
			continue
		fi
		cutline=$(echo "$line" |sed 's/	//')
		printf "%${ind}s${cutline}\n"
		print_tree "$cutline" $((ind+tab))
	done
)
}

mode="$1"
target="$2"

if [ -z "$mode" ] \
    || ([ "$mode" != '-r' ] \
    && [ "$mode" != '-d' ]) \
    || [ -z "$target" ]; then
	echo "usage: pkg-tree <-r|-d> <package>" 1>&2
	exit 1
fi

tab=4
first=1

print_tree "$target" $tab
