#!/bin/sh
#this is a very simple script
#that obtains the present working
#directory (pwd) for currently focused
#window. in fact, it looks for the
#sh(1) process (the last one) under
#the focused window and prints it's pwd.
#it requires the `xii` utility to be
#present in the system's PATH.
#also `xprop` we need.

#you may find this script helpful
#for opening a new terminal emulator
#with your *current* terminal window
#path opened. So do I with i3wm.

xii=$(xii)
pid=$(xprop -id "$xii"|grep _NET_WM_PID |sed 's/.*= //')
ps -j \
|grep "$pid" \
|grep " /bin/sh$" \
|tail -n1 \
|tr -s ' ' \
|cut -d ' ' -f2 \
|xargs pwdx \
|sed 's/.* //'
